config/routes.rb
Rails.application.routes.draw do
  root "blog_posts#index"

  resources :blog_posts
  resources :comments, only: [:edit, :update, :destroy, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	validates :title, :blog_entry, presence: true
	validates :title, length: {maximum: 140, too_short: "Post cannot exceed 140 characters"}
	has_many :comments, dependent: :destroy #depdent destroy will delete comments with post deletion
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog_post
	validates :comment_entry, :blog_post_id, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy] #sets the set_blog_post private method to the show, edit, update, and destroy methods.

  def index
  	@blog_posts = BlogPost.all
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def new
  	@blog_post = BlogPost.new
  end

  def create
  	@blog_post = BlogPost.new(blog_post_params)
  	respond_to do |format|
  		if @blog_post.save
  			format.html {redirect_to blog_post_url(@blog_post), notice: "Post was created!!"}
  		else
  			format.html {render :new}
  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @blog_post.update(blog_post_params)
  			format.html{redirect_to blog_post_url(@blog_post), notice: "Post was updated!!"}
  		else
  			format.html{render :edit}
  		end
  	end
  end

  def destroy
  	@blog_post.destroy
  	respond_to do |format|
  		format.html {redirect_to root_url, notice: "Post was deleted!!"}
  	end
  end

  private #this is for security!!

  def blog_post_params
  	params.require(:blog_post).permit(:title, :blog_entry, :author)
  end

  def set_blog_post
  	@blog_post = BlogPost.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:edit, :update, :destroy]
  def edit
  end

  def create
  	@comment = Comment.new(comment_params)
  	respond_to do |format|
  		if @comment.save
  			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was created!!"}
  		else
  			format.html {render :back, notice: "Comment failed to post."}
  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @comment.update(comment_params)
  			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was updated successfully!!"}
  		else
  			format.html {render :edit}
  		end
  	end
  end

  def destroy
  	@comment.destroy
  	respond_to do |format|
  		format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was deleted!!"}
  	end
  end

  private

  def set_comment
  	@comment = Comment.find(params[:id])
  end

  def comment_params
  	params.require(:comment).permit(:author, :comment_entry, :blog_post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>
<% if @blog_post.errors.any? %>
<div class="error_explanation">
	<h2><%= pluralize(@blog_post.errors.count, "Error")%> Prohbiited this blog post from being made:</h2>
	<ul>
		<%= @blog_post.errors.full_messages.each do |message| %>
		<li><% message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="form-group">
	<div class="form-group">
		<%= form.text_field :title, class: "form-control", placeholder: "Title" %>
	</div>
	
	<div class="form-group">
		<%= form.text_field :author, class: "form-control", placeholder: "Name" %>
	</div>
	
	<div class="form-group">
		<%= form.text_area :blog_entry, class: "form-control", placeholder: "Type in post", rows: 12 %>
	</div>
	
	<div class="form-group">
		<%= form.submit "Post", class: "btn btn-primary" %>
	</div>
</div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %><br>
<%= link_to 'Back', blog_post_url(@blog_post), class: "btn btn-info" %>
<%= link_to 'View All Posts', root_url, class: "btn btn-info" %>

app/views/blog_posts/index.html.erb
<h1>All Posts</h1>
<div class="row">
	<% @blog_posts.each do |blog_post| %>
<div style="padding: 5px; width: 20rem;" class="" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= link_to blog_post.title, blog_post_path(blog_post) %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p style="word-wrap: break-word;">By: <%= blog_post.author%></p>
        <p style="word-wrap: break-word;"><%= blog_post.blog_entry.truncate(10)%> <%=link_to 'Read More', blog_post %></p>
        <small><i>Created <%= blog_post.created_at.strftime('%m/%d/%Y at %I:%M%p')%> ago</i></small>
      </div>
      <div class="modal-footer" style="justify-content: center;">
      	<%= link_to 'Edit Post', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
      	<%= link_to 'Delete Post', blog_post_path(blog_post), method: :delete, data: {confirm: "Are you sure you want to delete this post?"}, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>
  <% end %>
</div>
<%= link_to 'New Post', new_blog_post_path, class: "btn btn-success"%>

app/views/blog_posts/new.html.erb
<h1>Create A New Post</h1>
<%= render 'form' %><br>
<%= link_to "View All Posts", blog_posts_url, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<div class="" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= @blog_post.title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="word-wrap: break-word;">
        <p><%= @blog_post.author%></p>
        <p><%= @blog_post.blog_entry%></p>
        <small>Created <%= time_ago_in_words(@blog_post.created_at)%> ago</small>
      </div>
      <div class="modal-footer">
        <%= link_to 'Edit', edit_blog_post_url(@blog_post), class: "btn btn-warning"%>
        <%= link_to 'View All Posts', root_url, class: "btn btn-primary"%>
      </div>
    </div>
  </div>
</div>

<div class="" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Make a comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="word-wrap: break-word;">
        <%= render 'comments/form' %>
      </div>
    </div>
  </div>
</div>

<div class="" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">All Comments</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="word-wrap: break-word;">
        <p><%= render 'comments/comments' %></p>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', root_url, class: "btn btn-primary" %>

app/views/comments/_comments.html.erb
<% @blog_post.comments.each do |comment| %>
	<h3><%= comment.author%></h3>
	<p><%= comment.comment_entry%></p>
	<small>Created <%= time_ago_in_words(comment.created_at)%> ago</small><hr>
<%end%>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>
<% if @comment.errors.any? %>
<div class="error_explanation">
	<h2><%= pluralize(@comment.errors.count, "Error")%> Prohbiited this comment from being made:</h2>
	<ul>
		<%= @comment.errors.full_messages.each do |message| %>
		<li><% message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="form-group">
	<div class="form-group">
		<%= form.text_field :author, class: "form-control", placeholder: "Title" %>
	</div>
	
	<div class="form-group">
		<%= form.text_field :comment_entry, class: "form-control", placeholder: "Type comment here...", rows: 4 %>
	</div>
	
	<div class="form-group">
		<%= form.hidden_field :blog_post_id, value: @blog_post.id%>
	</div>
	
		<%= form.submit "Post", class: "btn btn-primary" %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    <%= yield %>
	</div>
  </body>
</html>